// This file is generated by kxml_compiler from occinfo.xml.

// #include <QString>
// #include <QDomElement>
// #include <QXmlStreamWriter>

namespace OCC {

class UpdateInfo {
public:
    void setVersion (QString &v);
    QString version () const;
    void setVersionString (QString &v);
    QString versionString () const;
    void setWeb (QString &v);
    QString web () const;
    void setDownloadUrl (QString &v);
    QString downloadUrl () const;
    /**
      Parse XML object from DOM element.
     */
    static UpdateInfo parseElement (QDomElement &element, bool *ok);
    static UpdateInfo parseString (QString &xml, bool *ok);

private:
    QString mVersion;
    QString mVersionString;
    QString mWeb;
    QString mDownloadUrl;
};

} // namespace OCC

#endif // UPDATEINFO_H
