// This file is generated by kxml_compiler from occinfo.xml.

// #include <QString>
// #include <QDomElement>
// #include <QXmlStreamWriter>

namespace Occ {

class UpdateInfo {
public:
    void setVersion (QString &v);
    QString version ();
    void setVersionString (QString &v);
    QString versionString ();
    void setWeb (QString &v);
    QString web ();
    void setDownloadUrl (QString &v);
    QString downloadUrl ();
    /**
      Parse XML object from DOM element.
     */
    static UpdateInfo parseElement (QDomElement &element, bool *ok);
    static UpdateInfo parseString (QString &xml, bool *ok);

private:
    QString mVersion;
    QString mVersionString;
    QString mWeb;
    QString mDownloadUrl;
};

} // namespace Occ
